name: Deploy to App Distribution

on: 
  - workflow_dispatch

permissions:
  contents: read
  id-token: write

jobs:
  build:

    runs-on: macos-12
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v1
    - id: auth
      uses: 'google-github-actions/auth@v1.0.0'
      with:
          workload_identity_provider: projects/595091170546/locations/global/workloadIdentityPools/firebase-app-distribution/providers/github-actions
          service_account: firebase-app-distribution@actionsandappdistributiontest.iam.gserviceaccount.com
          token_format: access_token
    - name: Deploy to Firebase App Distribution
      env:
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }} # In case of using manual certificates import
        PERSONAL_ACCESS_TOKEN_GITHUB: ${{ secrets.PERSONAL_ACCESS_TOKEN_GITHUB }} # In case of using match
        MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }} # In case of using match
        FIREBASE_ACCESS_TOKEN: ${{ steps.auth.outputs.access_token }}
      run: |
        bundle install
        bundle exec fastlane app_distribution

